name: CI/CD-Pipeline (Build, Test and Deploy)

# Controls when the workflow will run
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker (If Docker is required for the build)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker Image of Application
      - name: Build Application
        run: |
          chmod +x ./scripts/build-backend.sh  # Ensure the script is executable
          ./scripts/build-backend.sh
        env:
          DOCKER_HUB_TOCKEN: ${{ secrets.DOCKER_HUB_TOCKEN }} 

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      # Step 4: Deploy Application to EC2
      - name: Deploy Application
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        env:
          AWS_EC2_ACCESS_KEY: ${{ secrets.AWS_EC2_ACCESS_KEY }}    